### PR TITLE
Everything finished according to instructions

### PR DESCRIPTION
**Pull request by edlingao**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, amazing job on using bootstrap. Here are a few tweaks recommended to take the project to the next level.
 - All images should be responsive i.e., [here](https://snag.gy/7zxT6q.jpg), [here](https://snag.gy/FN3oAE.jpg), [here](https://snag.gy/foSDWw.jpg), [here](https://snag.gy/emBJp3.jpg).
 - No need to use too much CSS as you can use most [utility](https://getbootstrap.com/docs/4.3/utilities/borders/) classes from bootstrap.
 - Always use custom CSS at the end of `head` tag(before `title` to override others) like this:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="css/main.css" type="text/css">
    <title>Newsweek</title>
</head>
```
 - Fix [navbar](https://snag.gy/IDlA2W.jpg)

Once fixed, kindly resubmit your project.

**Comment by edlingao** [comment]
Everything is fixed now! nice day

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, amazing job. Everything is fixed now. Kindly look into the viewports between yours and original site by zooming in/out. There is still left/right extra white spaces. Kindly fix that as well.
Once fixed, kindly resubmit for review.

**Comment by edlingao** [comment]
Fixed extra spaces now!

**Review by inhaq — APPROVED** [review]
Good job on fixing, it's 👍🏻

**Pull request merged**
